apiVersion: v1
kind: Service
metadata:
  name: epsilon-shipops-service
spec:
  selector:
    app: epsilon-shipops
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: NodePort
